name: Build Windows Client EXE

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        # We only install CPU versions for the lightweight client
        pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cpu
        # Install wxpython for the UI
        pip install wxpython requests Pillow onnxruntime-openvino numpy scipy protobuf pynput mediapipe==0.10.11 opencv-python pyanime4k==3.1.0 pyvirtualcam==0.9.1 pyopengl onnx tqdm OneEuroFilter sounddevice brotli
        pip install pyinstaller

    - name: Build EXE with PyInstaller
      run: |
        # We only bundle the launcher code. Models are downloaded at runtime from the GitHub server.
        pyinstaller --noconfirm --onedir --windowed --name "EasyVtuberClient"  "launcher2.py"
        
    - name: Create ZIP
      run: |
        Compress-Archive -Path dist\EasyVtuberClient\* -DestinationPath EasyVtuberClient.zip

    - name: Create Release and Upload Client
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: EasyVtuberClient.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
